/* Merges two copies of a student's progress (e.g. this device's and the
 * cloud's) into one, so a device that's behind never overwrites one that's
 * ahead. Pure and order-independent: merge(a, b) and merge(b, a) agree on
 * everything except `name`, where `a` (the local copy) wins.
 *
 * Records carry an `at` timestamp (ms). Deleting a record (a teacher's
 * reset) leaves a tombstone in `removed`, and erasing everything sets
 * `epoch` — a record only survives if it is newer than whichever of those
 * applies to it, which is what stops a stale device from resurrecting
 * something that was reset elsewhere.
 */
(function (root) {
  const COLLS = ["completed", "grammarDone", "homeworkDone", "roleplay"];

  // Realtime Database hands back an Array (with null holes) for any object
  // whose keys look like 0..n — "completed" keyed by day number does.
  function asObj(v) {
    if (!v || typeof v !== "object") return {};
    if (!Array.isArray(v)) return v;
    const o = {};
    v.forEach((x, i) => { if (x != null) o[i] = x; });
    return o;
  }

  /* DAY_MAP:BEGIN (generated by scripts/merge-speakup-curriculum.mjs) */
  const DAY_MAP = {"1":[1,2],"2":[3],"3":[4],"4":[6,7],"5":[5],"6":[8,9],"7":[11],"8":[12],"9":[13,14],"10":[10,15],"11":[16,17],"12":[18],"13":[19],"14":[21,22],"15":[20],"16":[23,24],"17":[26,27],"18":[28],"19":[29],"20":[25,30],"21":[31],"22":[32,33],"23":[34],"24":[36,37],"25":[35],"26":[38],"27":[39],"28":[41,42],"29":[43,44],"30":[40,45],"31":[46,47],"32":[48],"33":[49],"34":[51,52],"35":[50],"36":[53,54],"37":[56,57],"38":[58],"39":[59],"40":[55,60],"41":[61,62],"42":[63],"43":[64],"44":[66,67],"45":[65],"46":[68,69],"47":[71,72],"48":[73],"49":[74],"50":[70,75],"51":[76,77],"52":[78],"53":[79],"54":[81,82],"55":[80],"56":[83,84],"57":[86],"58":[87],"59":[88,89],"60":[85,90]};
  /* DAY_MAP:END */

  // The course was condensed from 90 to 60 lessons (see scripts/merge-speakup-
  // curriculum.js). Progress saved under the old day numbers has no `schema`
  // (or schema < 2); this converts it once. A new lesson counts as completed
  // only when ALL the old lessons it was made from were; a teacher's reset of
  // ANY of them (a tombstone) resets the new lesson. Nothing else is touched:
  // grammar units and homework sessions are keyed by id / vocabulary position,
  // which the merge did not change.
  function remapColl(coll, kind) {
    const out = {};
    Object.keys(DAY_MAP).forEach((nd) => {
      const olds = DAY_MAP[nd];
      const es = olds.map((o) => coll[o]);
      if (es.some((e) => !e)) return;
      const at = Math.max.apply(null, es.map((e) => e.at || 0));
      const last = es.reduce((a, b) => ((b.at || 0) >= (a.at || 0) ? b : a));
      if (kind === "roleplay") {
        out[nd] = Object.assign({}, last, { best: Math.round(es.reduce((a, e) => a + (e.best || 0), 0) / es.length), at });
      } else {
        out[nd] = Object.assign({}, last, { score: Math.round(es.reduce((a, e) => a + (e.score || 0), 0) / es.length), at });
      }
    });
    return out;
  }
  function remapRemoved(rem) {
    const out = {};
    Object.keys(DAY_MAP).forEach((nd) => {
      const t = Math.max.apply(null, DAY_MAP[nd].map((o) => rem[o] || 0));
      if (t > 0) out[nd] = t;
    });
    return out;
  }
  function migrate(p) {
    p = p || {};
    if (Number(p.schema) >= 2) return p;
    const out = Object.assign({}, p, { schema: 2 });
    out.completed = remapColl(asObj(p.completed), "completed");
    out.roleplay = remapColl(asObj(p.roleplay), "roleplay");
    const r = asObj(p.removed);
    out.removed = Object.assign({}, r, { completed: remapRemoved(asObj(r.completed)), roleplay: remapRemoved(asObj(r.roleplay)) });
    return out;
  }

  function normalize(p) {
    p = migrate(p || {});
    const n = Object.assign({}, p);
    COLLS.forEach((c) => { n[c] = asObj(p[c]); });
    n.appliedResets = asObj(p.appliedResets);
    n.appliedPasses = asObj(p.appliedPasses);
    const r = asObj(p.removed);
    n.removed = {};
    COLLS.forEach((c) => { n.removed[c] = asObj(r[c]); });
    n.epoch = Number(p.epoch) || 0;
    n.xp = Number(p.xp) || 0;
    n.streak = Number(p.streak) || 0;
    delete n.updatedAt;
    return n;
  }

  function pickEntry(coll, ea, eb) {
    if (!ea) return eb;
    if (!eb) return ea;
    if (coll === "roleplay") {
      const hi = (eb.best || 0) > (ea.best || 0) ? eb : ea;
      return Object.assign({}, hi, { best: Math.max(ea.best || 0, eb.best || 0), at: Math.max(ea.at || 0, eb.at || 0) });
    }
    const ta = ea.at || 0, tb = eb.at || 0;
    if (ta !== tb) return ta > tb ? ea : eb;
    return (eb.score || 0) > (ea.score || 0) ? eb : ea;
  }

  function derivedXp(m) {
    let xp = 0;
    Object.values(m.completed).forEach((e) => { xp += 100 + (e.score || 0) * 5; });
    Object.values(m.grammarDone).forEach((e) => { xp += 60 + (e.score || 0) * 3; });
    Object.values(m.homeworkDone).forEach((e) => { xp += 80 + (e.score || 0) * 3; });
    xp += Object.keys(m.roleplay).length * 30;
    return xp;
  }

  function sameKeys(side, m) {
    return COLLS.every((c) => {
      const a = Object.keys(side[c]).sort().join(",");
      const b = Object.keys(m[c]).sort().join(",");
      return a === b;
    });
  }

  function merge(localRaw, remoteRaw) {
    const A = normalize(localRaw), B = normalize(remoteRaw);
    const m = Object.assign({}, B, A);

    m.epoch = Math.max(A.epoch, B.epoch);
    m.removed = {};
    COLLS.forEach((c) => {
      const out = {};
      new Set(Object.keys(A.removed[c]).concat(Object.keys(B.removed[c]))).forEach((k) => {
        out[k] = Math.max(A.removed[c][k] || 0, B.removed[c][k] || 0);
      });
      m.removed[c] = out;
    });

    COLLS.forEach((c) => {
      const out = {};
      new Set(Object.keys(A[c]).concat(Object.keys(B[c]))).forEach((k) => {
        const e = pickEntry(c, A[c][k], B[c][k]);
        const cut = Math.max(m.removed[c][k] || 0, m.epoch);
        if (cut > 0 && (e.at || 0) <= cut) return;
        out[k] = e;
      });
      m[c] = out;
    });

    m.appliedResets = Object.assign({}, B.appliedResets, A.appliedResets);
    m.appliedPasses = Object.assign({}, B.appliedPasses, A.appliedPasses);
    m.name = A.name || B.name || "";

    const la = A.lastDate || "", lb = B.lastDate || "";
    if (la > lb) { m.lastDate = A.lastDate; m.streak = A.streak; }
    else if (lb > la) { m.lastDate = B.lastDate; m.streak = B.streak; }
    else { m.lastDate = A.lastDate || B.lastDate || null; m.streak = Math.max(A.streak, B.streak); }

    const aSame = sameKeys(A, m), bSame = sameKeys(B, m);
    m.xp = aSame && bSame ? Math.max(A.xp, B.xp) : aSame ? A.xp : bSame ? B.xp : derivedXp(m);

    delete m.updatedAt;
    return m;
  }

  function canon(v) {
    if (Array.isArray(v)) return v.map(canon);
    if (v && typeof v === "object") {
      const o = {};
      Object.keys(v).sort().forEach((k) => { o[k] = canon(v[k]); });
      return o;
    }
    return v;
  }
  // Stable string for "are these two copies the same?" — ignores updatedAt
  // and the array-vs-object quirk of Realtime Database.
  function signature(p) { return JSON.stringify(canon(normalize(p))); }

  const api = { merge, signature, normalize, migrate, DAY_MAP };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  root.SU_progressMerge = api;
})(typeof window !== "undefined" ? window : globalThis);
